# Where things are
source              : .
destination         : ./_site
collections_dir     : .
plugins_dir         : _plugins # takes an array of strings and loads plugins in that order
layouts_dir         : _layouts
data_dir            : _data
includes_dir        : _includes
sass:
  sass_dir: _sass
collections:
  posts:
    output          : true

# Handling Reading
safe                : false
include             : [".htaccess"]
exclude             : ["Gemfile", "Gemfile.lock", "node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/"]
keep_files          : [".git", ".svn"]
encoding            : "utf-8"

markdown_ext        : "markdown,mkdown,mkdn,mkd,md"
strict_front_matter : false

# Filtering Content
show_drafts         : null
limit_posts         : 0
future              : false
unpublished         : false

# Plugins
whitelist           : []
plugins             : []

# Conversion
markdown            : kramdown
highlighter         : rouge
lsi                 : false
excerpt_separator   : "\n\n"
incremental         : false

# Serving
detach              : false
port                : 4000
host                : 127.0.0.1
baseurl             : "" # does not include hostname
show_dir_listing    : false

# Outputting
permalink           : date
paginate_path       : /page:num
timezone            : null

quiet               : false
verbose             : false
defaults            : []

liquid:
  error_mode        : warn
  strict_filters    : false
  strict_variables  : false

# Markdown Processors
kramdown:
  auto_ids          : true
  entity_output     : as_char
  toc_levels        : [1, 2, 3, 4, 5, 6]
  smart_quotes      : lsquo,rsquo,ldquo,rdquo
  input             : GFM
  hard_wrap         : false
  footnote_nr       : 1
  show_warnings     : false
  
title: Your awesome title
author:
  name: GitHub User
  email: your-email@domain.com

description: >
  Write an awesome description for your new site here. You can edit this line
  in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

sass:
  quiet_deps: true
  silence_deprecations: [import]

minima:
  # Minima skin selection. Available skins are:
  #   Available skins:
  #     * classic            Default, light color scheme.
  #     * dark               Dark variant of the classic skin.
  #     * auto               Adaptive skin based on the default classic and dark skins.
  #     * solarized-light    Light variant of solarized color scheme.
  #     * solarized-dark     Dark variant of solarized color scheme.
  #     * solarized          Adaptive skin for solarized color scheme skins.
  skin: classic

  # Specific pages for site navigation.
  #   If you wish to link only specific pages in the site-navigation, use this and list
  #   the `path` property (as represented via Liquid) of the pages in the order they
  #   should be rendered.
  nav_pages:
    - about.md

  # Set to `true` to show excerpts on the homepage.
  show_excerpts: false

  # Minima date format.
  #   The default value is "%b %d, %Y" (e.g. Nov 14, 2023).
  #   Refer to https://shopify.github.io/liquid/filters/date/ for valid values.
  # date_format: "%b-%d-%Y"

  # Social Media Links
  #   Renders icons via Font Awesome Free webfonts CDN, based on ordered list of entries.
  #   Entry keys:
  #     * title    Tooltip rendered on hovering over icon.
  #     * icon     Font Awesome icon id. `github` corresponds to `fa-github`.
  #     * url      Full URL of social profile.
  social_links:
    - title: Minima Theme repository at GitHub
      icon: github
      url: "https://github.com/jekyll/minima"
    - title: Jekyll at X (formerly Twitter)
      icon: x-twitter
      url: "https://x.com/jekyllrb"
      
